import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowUpRight, Boxes, CircleDollarSign, Plus, ShoppingCart, Users } from 'lucide-react'
import { AppLayout } from './components/layout/AppLayout'
import { Badge } from './components/ui/Badge'
import { Button } from './components/ui/Button'
import { Card } from './components/ui/Card'
import { Input } from './components/ui/Input'
import { Modal } from './components/ui/Modal'
import { Table } from './components/ui/Table'
import { useAppStore } from './store/useAppStore'
import type { Pestana, Producto, Venta, Cliente } from './types'

const moneda = new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'USD' })

function App() {
  const [pestana, setPestana] = useState<Pestana>('Resumen')
  const [menuAbierto, setMenuAbierto] = useState(false)
  const [modalAbierto, setModalAbierto] = useState(false)
  const productos = useAppStore((state) => state.productos)
  const ventas = useAppStore((state) => state.ventas)
  const clientes = useAppStore((state) => state.clientes)
  const filtros = useAppStore((state) => state.filtros)
  const agregarProducto = useAppStore((state) => state.agregarProducto)
  const [nuevoProducto, setNuevoProducto] = useState({ nombre: '', categoria: 'Tecnología', precio: 0, stock: 0, stockMinimo: 5 })
  const productosVisibles = productos.filter((producto) => producto.nombre.toLowerCase().includes(filtros.termino.toLowerCase()))
  const guardarProducto = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); agregarProducto(nuevoProducto); setNuevoProducto({ nombre: '', categoria: 'Tecnología', precio: 0, stock: 0, stockMinimo: 5 }); setModalAbierto(false) }
  return <AppLayout pestana={pestana} cambiar={setPestana} menuAbierto={menuAbierto} setMenuAbierto={setMenuAbierto}><div className="mx-auto max-w-7xl animate-[aparecer_.4s_ease-out]"><div className="mb-7 flex items-end justify-between"><div><p className="mb-1 text-sm font-semibold text-verde">Resumen operativo</p><h2 className="font-display text-3xl font-bold tracking-tight text-tinta">Buenos días, Ana <span aria-hidden="true">✦</span></h2><p className="mt-2 text-sm text-slate-500">Aquí tienes lo que está pasando en tu negocio.</p></div>{pestana === 'Productos' && <Button onClick={() => setModalAbierto(true)}><Plus size={17} />Nuevo producto</Button>}</div>{pestana === 'Resumen' && <Resumen productos={productos} ventas={ventas} clientes={clientes} />}{pestana === 'Productos' && <Productos productos={productosVisibles} />}{pestana === 'Ventas' && <Ventas ventas={ventas} />}{pestana === 'Clientes' && <Clientes clientes={clientes} />}<Modal abierto={modalAbierto} cerrar={() => setModalAbierto(false)} titulo="Registrar producto"><form onSubmit={guardarProducto} className="space-y-4"><Input etiqueta="Nombre del producto" required value={nuevoProducto.nombre} onChange={(event) => setNuevoProducto({ ...nuevoProducto, nombre: event.target.value })} placeholder="Ej. Monitor UltraWide" /><div className="grid grid-cols-2 gap-4"><Input etiqueta="Precio" type="number" min="0" step="0.01" required value={nuevoProducto.precio} onChange={(event) => setNuevoProducto({ ...nuevoProducto, precio: Number(event.target.value) })} /><Input etiqueta="Stock inicial" type="number" min="0" required value={nuevoProducto.stock} onChange={(event) => setNuevoProducto({ ...nuevoProducto, stock: Number(event.target.value) })} /></div><Button type="submit" className="mt-3 w-full">Guardar producto</Button></form></Modal></div></AppLayout>
}

function Resumen({ productos, ventas, clientes }: { productos: Producto[]; ventas: Venta[]; clientes: Cliente[] }) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metrica icono={<CircleDollarSign />} etiqueta="Ventas del mes" valor="$12,480" cambio="+18.4%" color="bg-emerald-50 text-verde" /><Metrica icono={<ShoppingCart />} etiqueta="Pedidos" valor="248" cambio="+12.6%" color="bg-orange-50 text-orange-600" /><Metrica icono={<Users />} etiqueta="Clientes activos" valor={String(clientes.length * 47)} cambio="+8.2%" color="bg-sky-50 text-sky-600" /><Metrica icono={<Boxes />} etiqueta="Productos" valor={String(productos.length)} cambio="2 por reponer" color="bg-rose-50 text-coral" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Card className="p-5"><div className="mb-6 flex items-center justify-between"><div><h3 className="font-display text-lg font-bold text-tinta">Rendimiento de ventas</h3><p className="text-xs text-slate-400">Ingresos de los últimos 7 días</p></div><span className="text-sm font-bold text-verde">$3,842.50</span></div><div className="flex h-48 items-end gap-3 border-b border-slate-100 px-2">{[34, 52, 42, 68, 57, 82, 74].map((altura, indice) => <div key={indice} className="group flex flex-1 flex-col items-center gap-2"><div style={{ height: `${altura}%` }} className={`w-full max-w-10 rounded-t-md transition ${indice === 6 ? 'bg-coral' : 'bg-verde/20 group-hover:bg-verde/45'}`} /><span className="text-[10px] text-slate-400">{['L', 'M', 'X', 'J', 'V', 'S', 'D'][indice]}</span></div>)}</div></Card><Card className="p-5"><div className="mb-5 flex items-center justify-between"><h3 className="font-display text-lg font-bold text-tinta">Stock bajo</h3><span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-bold text-coral">2 alertas</span></div><div className="space-y-4">{productos.filter((producto) => producto.stock <= producto.stockMinimo).map((producto) => <div className="flex items-center justify-between" key={producto.id}><div><p className="text-sm font-bold text-tinta">{producto.nombre}</p><p className="text-xs text-slate-400">Mínimo: {producto.stockMinimo} unidades</p></div><span className="text-sm font-bold text-coral">{producto.stock} uds.</span></div>)}</div></Card></div><Card className="mt-6"><div className="flex items-center justify-between p-5"><h3 className="font-display text-lg font-bold text-tinta">Últimas ventas</h3><ArrowUpRight size={18} className="text-slate-400" /></div><Table columnas={['ID', 'Cliente', 'Artículos', 'Total', 'Fecha', 'Estado']}><VentasFilas ventas={ventas.slice(0, 3)} /></Table></Card></> }
function Metrica({ icono, etiqueta, valor, cambio, color }: { icono: ReactNode; etiqueta: string; valor: string; cambio: string; color: string }) { return <Card className="p-5"><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-lg ${color}`}>{icono}</div><span className="text-xs font-bold text-verde">{cambio}</span></div><p className="mt-5 text-sm font-semibold text-slate-500">{etiqueta}</p><p className="mt-1 font-display text-2xl font-bold text-tinta">{valor}</p></Card> }
function Productos({ productos }: { productos: Producto[] }) { return <Card><Table columnas={['Producto', 'Categoría', 'Precio', 'Stock', 'Estado']}><tbody>{productos.map((producto) => <tr className="border-b border-slate-50 last:border-0" key={producto.id}><td className="px-5 py-4 font-bold text-tinta">{producto.nombre}</td><td className="px-5 py-4 text-slate-500">{producto.categoria}</td><td className="px-5 py-4 font-semibold">{moneda.format(producto.precio)}</td><td className="px-5 py-4 font-semibold">{producto.stock} uds.</td><td className="px-5 py-4"><Badge tono={producto.estado === 'Agotado' ? 'rojo' : producto.stock <= producto.stockMinimo ? 'amarillo' : 'verde'}>{producto.estado === 'Agotado' ? 'Agotado' : producto.stock <= producto.stockMinimo ? 'Stock bajo' : 'Activo'}</Badge></td></tr>)}</tbody></Table></Card> }
function Ventas({ ventas }: { ventas: Venta[] }) { return <Card><Table columnas={['ID', 'Cliente', 'Artículos', 'Total', 'Fecha', 'Estado']}><VentasFilas ventas={ventas} /></Table></Card> }
function VentasFilas({ ventas }: { ventas: Venta[] }) { return <>{ventas.map((venta) => <tr className="border-b border-slate-50 last:border-0" key={venta.id}><td className="px-5 py-4 font-bold text-verde">{venta.id}</td><td className="px-5 py-4 font-semibold text-tinta">{venta.cliente}</td><td className="px-5 py-4 text-slate-500">{venta.productos}</td><td className="px-5 py-4 font-bold">{moneda.format(venta.total)}</td><td className="px-5 py-4 text-slate-500">{venta.fecha}</td><td className="px-5 py-4"><Badge tono={venta.estado === 'Completada' ? 'verde' : venta.estado === 'Pendiente' ? 'amarillo' : 'rojo'}>{venta.estado}</Badge></td></tr>)}</> }
function Clientes({ clientes }: { clientes: Cliente[] }) { return <Card><Table columnas={['Cliente', 'Correo', 'Teléfono', 'Compras', 'Estado']}><tbody>{clientes.map((cliente) => <tr className="border-b border-slate-50 last:border-0" key={cliente.id}><td className="px-5 py-4 font-bold text-tinta">{cliente.nombre}</td><td className="px-5 py-4 text-slate-500">{cliente.email}</td><td className="px-5 py-4 text-slate-500">{cliente.telefono}</td><td className="px-5 py-4 font-semibold">{cliente.compras}</td><td className="px-5 py-4"><Badge>{cliente.estado}</Badge></td></tr>)}</tbody></Table></Card> }
export default App
